// Generated via `npm run regen:pair-bans`
// Canonical unordered pair keys for curated standard-family bans.
export const CURATED_STANDARD_PAIR_BAN_REASONS: Record<string, string> = {
  'company:activision|game_mode:battle-royale': '3 or fewer catalog matches in curated pair table',
  'company:activision|game_mode:mmo': '3 or fewer catalog matches in curated pair table',
  'company:activision|platform:nes': '3 or fewer catalog matches in curated pair table',
  'company:activision|platform:switch-2': '3 or fewer catalog matches in curated pair table',
  'company:activision|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'company:capcom|game_mode:battle-royale': '3 or fewer catalog matches in curated pair table',
  'company:capcom|game_mode:mmo': '3 or fewer catalog matches in curated pair table',
  'company:capcom|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'company:capcom|platform:n64': '3 or fewer catalog matches in curated pair table',
  'company:electronic-arts|platform:3ds': '3 or fewer catalog matches in curated pair table',
  'company:electronic-arts|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'company:electronic-arts|platform:dc': '3 or fewer catalog matches in curated pair table',
  'company:electronic-arts|platform:gb': '3 or fewer catalog matches in curated pair table',
  'company:konami|game_mode:battle-royale': '3 or fewer catalog matches in curated pair table',
  'company:konami|game_mode:mmo': '3 or fewer catalog matches in curated pair table',
  'company:konami|platform:switch-2': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|game_mode:battle-royale':
    '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:3ds': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:dc': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:gb': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:gba': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:genesis-slash-megadrive':
    '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:n64': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:nds': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:nes': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:ngc': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:ps': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:psp': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:saturn': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:snes': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:switch-2': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:wii': '3 or fewer catalog matches in curated pair table',
  'company:microsoft-xbox|platform:wiiu': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|game_mode:battle-royale': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|game_mode:mmo': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:dc': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:ps': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:ps2': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:ps3': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:ps5': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:psp': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:psvita': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:saturn': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:series-x-s': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:xbox': '3 or fewer catalog matches in curated pair table',
  'company:nintendo|platform:xbox360': '3 or fewer catalog matches in curated pair table',
  'company:sega|game_mode:battle-royale': '3 or fewer catalog matches in curated pair table',
  'company:sega|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'company:sega|platform:gb': '3 or fewer catalog matches in curated pair table',
  'company:sega|platform:n64': '3 or fewer catalog matches in curated pair table',
  'company:sega|platform:nes': '3 or fewer catalog matches in curated pair table',
  'company:sony|decade:1980-01-01,1989-12-31': '3 or fewer catalog matches in curated pair table',
  'company:sony|game_mode:battle-royale': '3 or fewer catalog matches in curated pair table',
  'company:sony|game_mode:mmo': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:3ds': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:gb': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:gba': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:genesis-slash-megadrive':
    '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:nds': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:nes': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:ngc': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:snes': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:switch-2': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:wiiu': '3 or fewer catalog matches in curated pair table',
  'company:sony|platform:xbox': '3 or fewer catalog matches in curated pair table',
  'company:square-enix|game_mode:battle-royale': '3 or fewer catalog matches in curated pair table',
  'company:square-enix|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'company:square-enix|platform:genesis-slash-megadrive':
    '3 or fewer catalog matches in curated pair table',
  'company:square-enix|platform:ngc': '3 or fewer catalog matches in curated pair table',
  'company:thq|decade:1980-01-01,1989-12-31': '3 or fewer catalog matches in curated pair table',
  'company:thq|decade:2020-01-01,2029-12-31': '3 or fewer catalog matches in curated pair table',
  'company:thq|game_mode:battle-royale': '3 or fewer catalog matches in curated pair table',
  'company:thq|genre:tactical': '3 or fewer catalog matches in curated pair table',
  'company:thq|platform:3ds': '3 or fewer catalog matches in curated pair table',
  'company:thq|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'company:thq|platform:dc': '3 or fewer catalog matches in curated pair table',
  'company:thq|platform:ps5': '3 or fewer catalog matches in curated pair table',
  'company:thq|platform:psvita': '3 or fewer catalog matches in curated pair table',
  'company:thq|platform:saturn': '3 or fewer catalog matches in curated pair table',
  'company:thq|platform:series-x-s': '3 or fewer catalog matches in curated pair table',
  'company:thq|platform:switch-2': '3 or fewer catalog matches in curated pair table',
  'company:thq|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'company:ubisoft|decade:1980-01-01,1989-12-31':
    '3 or fewer catalog matches in curated pair table',
  'company:ubisoft|game_mode:battle-royale': '3 or fewer catalog matches in curated pair table',
  'company:ubisoft|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'company:ubisoft|platform:dc': '3 or fewer catalog matches in curated pair table',
  'company:ubisoft|platform:gb': '3 or fewer catalog matches in curated pair table',
  'company:ubisoft|platform:genesis-slash-megadrive':
    '3 or fewer catalog matches in curated pair table',
  'company:ubisoft|platform:nes': '3 or fewer catalog matches in curated pair table',
  'company:ubisoft|platform:saturn': '3 or fewer catalog matches in curated pair table',
  'company:ubisoft|platform:snes': '3 or fewer catalog matches in curated pair table',
  'company:ubisoft|platform:switch-2': '3 or fewer catalog matches in curated pair table',
  'decade:1980-01-01,1989-12-31|game_mode:battle-royale':
    'modern online mode paired with an early decade',
  'decade:1980-01-01,1989-12-31|game_mode:mmo': 'modern online mode paired with an early decade',
  'decade:1980-01-01,1989-12-31|platform:3ds': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:atari2600': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:dc': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:gb': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:gba': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:genesis-slash-megadrive':
    'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:n64': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:nds': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:nes': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:ngc': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:pc': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:ps2': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:ps3': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:ps4--1': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:ps5': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:psp': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:psvita': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:saturn': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:series-x-s': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:snes': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:switch': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:switch-2': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:wii': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:wiiu': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:xbox': '3 or fewer catalog matches in curated pair table',
  'decade:1980-01-01,1989-12-31|platform:xbox360': 'platform is outside its supported decades',
  'decade:1980-01-01,1989-12-31|platform:xboxone': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|game_mode:battle-royale':
    'modern online mode paired with an early decade',
  'decade:1990-01-01,1999-12-31|game_mode:mmo': 'modern online mode paired with an early decade',
  'decade:1990-01-01,1999-12-31|platform:3ds': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:atari2600':
    '3 or fewer catalog matches in curated pair table',
  'decade:1990-01-01,1999-12-31|platform:gba': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:nds': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:ngc': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:ps2': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:ps3': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:ps4--1': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:ps5': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:psp': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:psvita': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:series-x-s': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:switch': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:switch-2': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:wii': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:wiiu': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:xbox': '3 or fewer catalog matches in curated pair table',
  'decade:1990-01-01,1999-12-31|platform:xbox360': 'platform is outside its supported decades',
  'decade:1990-01-01,1999-12-31|platform:xboxone': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|game_mode:battle-royale':
    '3 or fewer catalog matches in curated pair table',
  'decade:2000-01-01,2009-12-31|platform:3ds': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:atari2600': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:gb': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:genesis-slash-megadrive':
    'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:n64': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:nes': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:ps4--1': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:ps5': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:psvita': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:saturn': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:series-x-s': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:snes': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:switch': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:switch-2': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:wiiu': 'platform is outside its supported decades',
  'decade:2000-01-01,2009-12-31|platform:xboxone': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:atari2600': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:dc': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:gb': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:gba': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:genesis-slash-megadrive':
    'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:n64': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:nes': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:ngc': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:ps': '3 or fewer catalog matches in curated pair table',
  'decade:2010-01-01,2019-12-31|platform:ps2': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:ps5': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:saturn': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:series-x-s': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:snes': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:switch-2': 'platform is outside its supported decades',
  'decade:2010-01-01,2019-12-31|platform:xbox': '3 or fewer catalog matches in curated pair table',
  'decade:2020-01-01,2029-12-31|platform:3ds': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:atari2600': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:dc': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:gb': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:gba': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:genesis-slash-megadrive':
    'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:n64': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:nds': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:nes': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:ngc': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:ps': '3 or fewer catalog matches in curated pair table',
  'decade:2020-01-01,2029-12-31|platform:ps2': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:ps3': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:psp': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:psvita': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:saturn': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:snes': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:wii': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:wiiu': 'platform is outside its supported decades',
  'decade:2020-01-01,2029-12-31|platform:xbox': '3 or fewer catalog matches in curated pair table',
  'decade:2020-01-01,2029-12-31|platform:xbox360': 'platform is outside its supported decades',
  'game_mode:battle-royale|genre:sport': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:3ds': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:dc': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:gb': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:gba': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:genesis-slash-megadrive':
    '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:n64': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:nds': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:nes': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:ngc': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:ps': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:ps2': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:ps3': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:psp': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:psvita': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:saturn': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:snes': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:switch-2': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:wii': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:wiiu': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:xbox': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|platform:xbox360': '3 or fewer catalog matches in curated pair table',
  'game_mode:battle-royale|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'game_mode:co-operative|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'game_mode:co-operative|platform:gb': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:3ds': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:dc': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:gb': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:gba': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:genesis-slash-megadrive':
    '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:n64': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:nds': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:nes': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:ngc': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:ps': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:ps2': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:psp': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:psvita': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:saturn': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:snes': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:switch-2': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:wii': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:wiiu': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|platform:xbox': '3 or fewer catalog matches in curated pair table',
  'game_mode:mmo|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'game_mode:split-screen|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'genre:fighting|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'genre:racing|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'genre:rpg|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'genre:sport|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'genre:tactical|platform:atari2600': '3 or fewer catalog matches in curated pair table',
  'genre:tactical|platform:gb': '3 or fewer catalog matches in curated pair table',
  'genre:tactical|platform:genesis-slash-megadrive':
    '3 or fewer catalog matches in curated pair table',
  'genre:tactical|platform:n64': '3 or fewer catalog matches in curated pair table',
  'platform:atari2600|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'platform:atari2600|theme:open-world': '3 or fewer catalog matches in curated pair table',
  'platform:atari2600|theme:survival': '3 or fewer catalog matches in curated pair table',
  'platform:dc|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'platform:gb|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'platform:gb|theme:open-world': '3 or fewer catalog matches in curated pair table',
  'platform:gb|theme:survival': '3 or fewer catalog matches in curated pair table',
  'platform:gb|theme:warfare': '3 or fewer catalog matches in curated pair table',
  'platform:gba|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'platform:gba|theme:open-world': '3 or fewer catalog matches in curated pair table',
  'platform:gba|theme:survival': '3 or fewer catalog matches in curated pair table',
  'platform:genesis-slash-megadrive|theme:mystery':
    '3 or fewer catalog matches in curated pair table',
  'platform:genesis-slash-megadrive|theme:open-world':
    '3 or fewer catalog matches in curated pair table',
  'platform:genesis-slash-megadrive|theme:survival':
    '3 or fewer catalog matches in curated pair table',
  'platform:n64|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'platform:n64|theme:survival': '3 or fewer catalog matches in curated pair table',
  'platform:ngc|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'platform:saturn|theme:open-world': '3 or fewer catalog matches in curated pair table',
  'platform:snes|theme:mystery': '3 or fewer catalog matches in curated pair table',
  'platform:snes|theme:survival': '3 or fewer catalog matches in curated pair table',
  'platform:switch-2|theme:warfare': '3 or fewer catalog matches in curated pair table',
}

export function getCuratedStandardPairBanReason(pairKey: string): string | null {
  return CURATED_STANDARD_PAIR_BAN_REASONS[pairKey] ?? null
}
